version: "3.7"

services:
  api_go:
    image: api_go
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - redis
      - postgres

  redis:
    image: grokzen/redis-cluster:latest
    ports:
      - "7500:7500"
    environment:
      - IP=0.0.0.0
    restart: on-failure
    volumes:
      - redis:/var/lib/redis

  postgres:
    image: postgres:13.6
    volumes:
      - postgis-data:/var/lib/postgresql
      - ./db/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "bdb"
      POSTGRES_USER: "buser"
      POSTGRES_PASSWORD: "bpassword"
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"

volumes:
  postgis-data:
  redis: