version: "3"

volumes:
  dbbackups:
  postgis-data:
  redis:

services:
  api_go:
    image: api_go
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7.0-alpine
    ports:
      - "7500:7500"
    restart: on-failure
    volumes:
      - redis:/var/lib/redis

  postgres:
    image: postgres:13.6-alpine
    volumes:
      - postgis-data:/var/lib/postgresql
      - ./db/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "bdb"
      POSTGRES_USER: "buser"
      POSTGRES_PASSWORD: "bpassword"
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
