version: "3"

volumes:
  dbbackups:
  postgis-data:
  redis:

services:
  dashboard:
    image: dashboard
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - redis
      - postgres

  redis:
    image: "dashboard_redis"
    ports:
      - "7500:7500"
    restart: on-failure
    volumes:
      - redis:/var/lib/redis

  postgres:
    image: postgres:13.6-alpine
    volumes:
      - postgis-data:/var/lib/postgresql
      - $PWD/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      POSTGRES_DB: "bmstuDb"
      POSTGRES_USER: "bmstuUser"
      POSTGRES_PASSWORD: "pgpwd4bmstu"
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
